version: '3.8'
name: Inception

services:
    # nginx:
    #     container_name: nginx
    #     restart: always
    #     build:
    #         context: ./requirements/nginx
    #         dockerfile: Dockerfile
    #     networks:
    #         - wordpress-nginx
    #     ports:
    #         - 443:443
    #     environment:
    #         - DOMAIN_NAME = ${DOMAIN_NAME:?}
    #         - NAME = ${NAME:?}


    wordpress:
        container_name: wordpress
        # restart: always
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        networks:
            - wordpress-nginx
            - mariadb-wordpress

    # mariadb:
    #     container_name: mariadb
    #     # restart: always
    #     build:
    #         context: ./requirements/mariadb
    #         dockerfile: Dockerfile
    #     networks:
    #         - wordpress-nginx
    #     volumes:
    #         - db-data:/sys/fs/cgroup/
    #     environment:
    #         - SQL_DATABASE = ${SQL_DATABASE:?}
    #         - SQL_USER = ${SQL_USER:?}
    #         - SQL_PASSWORD = ${SQL_PASSWORD:?}

networks:
    wordpress-nginx:
        driver: bridge
    mariadb-wordpress:
        driver: bridge

volumes:
    db-data: