name: Inception

services:
    nginx:
        container_name: nginx
        restart: on-failure
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        volumes:
            - vol_wordpress:/var/www/wordpress
        networks:
            - inception
        ports:
            - 443:443
        depends_on:
            - wordpress

    wordpress:
        container_name: wordpress
        restart: on-failure
        volumes:
            - vol_wordpress:/var/www/wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        networks:
            - inception
        depends_on:
                - mariadb
        environment:
            - SQL_DATABASE=${SQL_DATABASE:?}
            - SQL_USER=${SQL_USER:?}
            - SQL_PASSWORD=${SQL_PASSWORD:?}
            - wp_DB_USER=${wp_DB_USER:?}
            - wp_DB_PASSWORD=${wp_DB_PASSWORD:?}
        expose:
            - 9000
            - 3306

    mariadb:
        container_name: mariadb
        restart: on-failure
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
            args:
                - SQL_DATABASE=${SQL_DATABASE:?}
                - SQL_USER=${SQL_USER:?}
                - SQL_PASSWORD=${SQL_PASSWORD:?}
                - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD:?}
                - wp_DB_USER=${wp_DB_USER:?}
                - wp_DB_PASSWORD=${wp_DB_PASSWORD:?}
        environment:
                - SQL_DATABASE=${SQL_DATABASE:?}
                - SQL_USER=${SQL_USER:?}
                - SQL_PASSWORD=${SQL_PASSWORD:?}
                - SQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD:?}
                - wp_DB_USER=${wp_DB_USER:?}
                - wp_DB_PASSWORD=${wp_DB_PASSWORD:?}
        networks:
            - inception
        volumes:
            - vol_mariadb:/var/lib/mysql
        expose:
            - 3306

# TODO do separate network
networks:
    inception:
        driver: bridge

volumes:
    vol_wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./volumes/wordpress
    vol_mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./volumes/mariadb