CREATE DATABASE IF NOT EXISTS ${SQL_DATABASE};

CREATE USER IF NOT EXISTS '${SQL_USER}'@'%' IDENTIFIED BY '${SQL_PASSWORD}';
CREATE USER IF NOT EXISTS '${wp_DB_USER}'@'%' IDENTIFIED BY '${wp_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON ${SQL_DATABASE}.* TO '${SQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${SQL_DATABASE}.* TO '${wp_DB_USER}'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY '${SQL_ROOT_PASSWORD}';
